import type { Metadata } from "next";
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< Updated upstream
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
=======
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
>>>>>>> 398b559 (done)
} from '@clerk/nextjs'
import { Outfit } from "next/font/google";
import "./globals.css";
import Home from "./components/Home";
import { Toaster } from "react-hot-toast";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Just Health",
  description: "Students Health Tracker App",
=======
import { Geist, Geist_Mono } from "next/font/google";
=======
import { Outfit } from "next/font/google";
>>>>>>> 6c4e3d4 (login)
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> Stashed changes
=======
  title: "Just Health",
  description: "Students Health Tracker App",
>>>>>>> 6c4e3d4 (login)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
<<<<<<< Updated upstream
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
      >
       <SignedIn>
        <Toaster/>
        {children}
      </SignedIn>
      <SignedOut>
        <div>
        <Home/>
        </div>
      </SignedOut>
      </body>
    </html>
    </ClerkProvider>
=======
=======
    <ClerkProvider>
>>>>>>> 398b559 (done)
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
<<<<<<< HEAD
>>>>>>> Stashed changes
=======
    </ClerkProvider>
>>>>>>> 398b559 (done)
  );
}
