import type { Metadata } from "next";
<<<<<<< Updated upstream
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs'
import { Outfit } from "next/font/google";
import "./globals.css";
import Home from "./components/Home";
import { Toaster } from "react-hot-toast";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Just Health",
  description: "Students Health Tracker App",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> Stashed changes
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< Updated upstream
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
      >
       <SignedIn>
        <Toaster/>
        {children}
      </SignedIn>
      <SignedOut>
        <div>
        <Home/>
        </div>
      </SignedOut>
      </body>
    </html>
    </ClerkProvider>
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
>>>>>>> Stashed changes
  );
}
